import type { Metadata } from "next";
import { PeydaWebFont } from "@/lib/localFont";
import "../styles/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={PeydaWebFont.variable}>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body>
        {children}
      </body>
    </html>
  );
}
